'use strict';
function studentMarkup(){return `<section id="students" class="section students"><div class="section-heading"><div><p class="eyebrow">FOR SECOND-YEAR STUDENTS</p><h2>${t('まだ、専門が決まっていなくても。','You don’t need all the answers yet.')}</h2></div><p>${t('「ちょっと気になる」が、研究の始まり。<br>まずは一つ、動かしてみませんか。','A little curiosity is a place to start.<br>Try making one thing work.')}</p></div><div class="student-layout"><div class="interest-picker"><h3>${t('あなたなら、何をつくる？','What would you like to create?')}</h3><p>${t('興味に近いものを選ぶと、最初の実験のアイデアが見つかります。','Choose an interest to find an idea for a first experiment.')}</p><div class="interest-buttons">${[['人の役に立つ','Help people'],['自然を知る','Understand nature'],['道具をつくる','Build tools'],['街を探検する','Explore places']].map((v,i)=>`<button data-interest="${i}" aria-pressed="${i===0}">${t(...v)}</button>`).join('')}</div><div id="interest-result" aria-live="polite"></div></div><div class="first-steps"><p class="eyebrow">A POSSIBLE FIRST STEP</p>${[['01','見る・触る','Look & try','研究デモで「なぜ？」を一つ見つける。','Find one question while trying a demo.'],['02','小さくつくる','Make something small','短いプログラムや身近なデータで試す。','Try a short program or an accessible dataset.'],['03','話して広げる','Discuss & explore','できたこと、難しかったことを持ち寄る。','Share what worked and what was difficult.']].map(([n,j,e,d,f])=>`<article><span>${n}</span><div><h3>${t(j,e)}</h3><p>${t(d,f)}</p></div></article>`).join('')}<a class="text-link" href="mailto:prima.lab.ipu@gmail.com?subject=${encodeURIComponent(t('学部2年生：研究室見学について','Second-year student: lab visit inquiry'))}">${t('まずは見学について相談する ↗','Ask about a lab visit ↗')}</a></div></div><div class="student-faq"><details><summary>${t('プログラミングに自信がなくても？','What if I’m not confident in programming?')}</summary><p>${t('まずはこのページのデモで条件を変えて、結果を説明してみてください。観察し、試し、考えることも研究の大切な入り口です。必要な基礎や学び方は、見学の際に相談できます。','Start by changing a demo’s conditions and explaining what happens. Observing, trying and reasoning are valuable first steps. Ask about useful foundations and ways to learn when you visit.')}</p></details><details><summary>${t('今から何を学べばよい？','What can I start learning now?')}</summary><p>${t('画像を一枚読み込む、座標を描く、データをグラフにする。授業で学んだ内容を、小さな「動くもの」にしてみましょう。研究テーマごとの最初の実験も上から選べます。','Load an image, plot coordinates or visualize a dataset. Turn something from class into a small working experiment. The choices above suggest starting points.')}</p></details><details><summary>${t('配属前に、研究の話を聞きたい。','Can I ask about research before joining?')}</summary><p>${t('興味のあるテーマや、見てみたいデモを書いてご連絡ください。見学の日時・参加方法は個別に相談します。正式な配属は学部の案内に従ってください。','Contact us with a topic or demo you are curious about. Visit arrangements can be discussed individually; formal lab allocation follows faculty procedures.')}</p></details></div></section>`}
function activityMarkup(){return `<section id="activities" class="section activities"><div class="section-heading"><div><p class="eyebrow">04 / LAB LIFE</p><h2>${t('つくる日も、<br>外へ出る日も。','Days of making.<br>Days of discovery.')}</h2></div><p>${t('研究は、一人の机の上だけでは終わらない。','Research continues beyond a single desk.')}</p></div><div class="activity-grid">${[
 ['01','MAKE & DISCUSS','試作と対話','Make & discuss','デモをつくり、動かして、問いを話す。思いどおりにいかなかった結果も、次に試すことのヒントになります。','Build a demo, try it and discuss the questions it raises. Unexpected results can suggest what to try next.'],
 ['02','LAB CAMPS','合宿と交流','Camps & connections','研究室ではイベントや夏・冬の合宿を通じた交流も行ってきました。いつもと違う場所で、制作や学びをともにする時間です。','The lab has held events and summer and winter camps: opportunities to create, learn and connect in a different setting.'],
 ['03','IN THE FIELD','地域とともにつくる','Create with communities','九戸城VRやインフラツーリズム。現地を知り、地域の知見を学び、伝わる体験へつなげる活動があります。','Kunohe Castle VR and infrastructure tourism connect field knowledge with experiences that communicate local stories.'],
 ['04','SHARE WITH THE WORLD','論文・国際会議で伝える','Share research internationally','英語論文や国際会議で研究を伝える。どんな問いに、どう取り組んだのかを、図とことばで説明します。','Papers and international conferences are opportunities to explain a research question and approach through figures and words.']
 ].map(([n,k,j,e,d,f])=>`<article><span class="activity-number">${n}</span><p class="eyebrow">${k}</p><h3>${t(j,e)}</h3><p>${t(d,f)}</p></article>`).join('')}</div><p class="caption">${t('これまでの活動の紹介です。開催日・見学のご案内はお問い合わせください。','An introduction to lab activities. Contact us for dates and visit arrangements.')}</p><div class="more-research"><figure><img src="assets/sphericul.jpg" width="1920" height="1080" loading="lazy" alt="Sphericul spherical display"><figcaption>Sphericul / PRIMA LAB</figcaption></figure><h3>${t('探究は、さらに広がる。','More directions to explore.')}</h3><div>${[['視線計測・人の行動','Eye tracking & behavior'],['画像AI・微小欠陥検出','Image AI & defect detection'],['Sphericul・空間ディスプレイ','Sphericul & spatial displays'],['PM2.5・環境センシング','PM2.5 & environmental sensing']].map((v,i)=>`<a href="${i===2?'https://www.prima-lab.org/':'#publications'}">${t(...v)} ↗</a>`).join('')}</div></div></section>`}
function mountCommunity(){
 const options=[{topic:0,title:['断面から立体を想像する','Imagine a volume from slices'],body:['超音波デモで断面を増やすと何が分かる？まずは座標と画像の関係を観察してみよう。','What changes as you add ultrasound slices? Start by observing the relationship between images and coordinates.']},{topic:2,title:['自分だけの枝のルールを考える','Invent a branching rule'],body:['光の条件を変えると形はどう変わる？授業で学んだ再帰やベクトルも、自然を表す道具になります。','How does light change the form? Recursion and vectors from class can become tools for modeling nature.']},{topic:3,title:['消したい背景、残したい線','Remove background, preserve lines'],body:['背景を減らしながら必要な線を守るには？画像を読み込み、明るさを調べるところから始められます。','How can you remove a background while preserving useful lines? Begin by loading an image and examining brightness.']},{topic:4,title:['街の「なぜ？」を伝える','Tell the story of a place'],body:['同じインフラを、技術者と見学者はどう見る？現地で伝えたいことを3つ考え、体験の順番にしてみよう。','How do engineers and visitors see the same infrastructure? Choose three things to communicate and arrange an experience.']}];
 function show(i){const p=options[i];document.querySelectorAll('[data-interest]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.interest===i)));document.querySelector('#interest-result').innerHTML=`<span>YOUR FIRST EXPERIMENT</span><h4>${t(...p.title)}</h4><p>${t(...p.body)}</p><button class="button dark" id="try-interest">${t('このテーマで遊んでみる ↑','Try this research ↑')}</button>`;document.querySelector('#try-interest').onclick=()=>{window.selectResearch(p.topic);document.querySelector('#research').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}
 document.querySelectorAll('[data-interest]').forEach(b=>b.onclick=()=>show(+b.dataset.interest));show(0);
}
