'use strict';
function studentMarkup(){return `<section id="students" class="section students"><div class="section-heading"><div><p class="eyebrow">FOR SECOND-YEAR STUDENTS</p><h2>${t('まだ，専門が決まっていなくても．','You don’t need all the answers yet.')}</h2></div><p>${t('「ちょっと気になる」が，研究の始まり．<br>まずは一つ，動かしてみませんか．','A little curiosity is a place to start.<br>Try making one thing work.')}</p></div><div class="quest-header"><div><p class="eyebrow">YOUR RESEARCH PASSPORT</p><h3>${t('5つの「できた！」を集めよう．','Collect five discoveries.')}</h3><p>${t('気になるミッションから出発．条件を変えて，研究の入り口を見つけよう．','Choose a mission. Change the conditions and find your way into research.')}</p></div><div class="quest-progress" aria-live="polite"><strong id="quest-count">0 / 5</strong><span>DISCOVERIES</span><small>${t('再読み込みでリセット','Resets on page reload')}</small><progress id="quest-meter" max="5" value="0" aria-label="${t('発見したテーマ数','Discovered topics')}"></progress></div></div><div class="quest-grid">${PRIMA_PROJECTS.map((p,i)=>`<button class="quest-card" data-quest="${i}"><span class="quest-number">0${i+1} <span class="quest-stamp"></span></span><small>${p.tag}</small><h3>${t(...[['断面を空間に並べる','Arrange slices in space'],['見えない信号を探る','Explore invisible signals'],['枝の未来を変える','Change a tree’s future'],['図面を立ち上げる','Bring a drawing to life'],['橋の下へ潜り込む','Look beneath a bridge']][i])}</h3><p>${p.challenge[lang==='en'?1:0]}</p><span class="quest-action">${t('ミッションに挑戦 ↗','Start mission ↗')}</span></button>`).join('')}</div><div class="quest-invite"><p>${t('うまくいった理由も，うまくいかない理由も，研究のタネ．<br>見つけた「なぜ？」を，研究室で話してみませんか．','What worked? What didn’t? Both can start a research question.<br>Bring your discoveries to a conversation at the lab.')}</p><a class="button dark" href="mailto:prima.lab.ipu@gmail.com?subject=Lab%20visit">${t('見学について相談する ↗','Ask about a lab visit ↗')}</a></div><div class="student-faq"><details><summary>${t('プログラミングに自信がなくても？','What if I’m not confident in programming?')}</summary><p>${t('まずはこのページのデモで条件を変えて，結果を説明してみてください．観察し，試し，考えることも研究の大切な入り口です．必要な基礎や学び方は，見学の際に相談できます．','Start by changing a demo’s conditions and explaining what happens. Observing, trying and reasoning are valuable first steps. Ask about useful foundations and ways to learn when you visit.')}</p></details><details><summary>${t('今から何を学べばよい？','What can I start learning now?')}</summary><p>${t('画像を一枚読み込む，座標を描く，データをグラフにする．授業で学んだ内容を，小さな「動くもの」にしてみましょう．研究テーマごとの最初の実験も上から選べます．','Load an image, plot coordinates or visualize a dataset. Turn something from class into a small working experiment. The choices above suggest starting points.')}</p></details><details><summary>${t('配属前に，研究の話を聞きたい．','Can I ask about research before joining?')}</summary><p>${t('興味のあるテーマや，見てみたいデモを書いてご連絡ください．見学の日時・参加方法は個別に相談します．正式な配属は学部の案内に従ってください．','Contact us with a topic or demo you are curious about. Visit arrangements can be discussed individually; formal lab allocation follows faculty procedures.')}</p></details></div></section>`}
function activityMarkup(){return `<section id="activities" class="section activities"><div class="section-heading"><div><p class="eyebrow">04 / LAB LIFE</p><h2>${t('つくる日も，<br>外へ出る日も．','Days of making.<br>Days of discovery.')}</h2></div><p>${t('研究は，一人の机の上だけでは終わらない．','Research continues beyond a single desk.')}</p></div><div class="activity-grid">${[
 ['01','MAKE & DISCUSS','試作と対話','Make & discuss','デモをつくり，動かして，問いを話す．思いどおりにいかなかった結果も，次に試すことのヒントになります．','Build a demo, try it and discuss the questions it raises. Unexpected results can suggest what to try next.'],
 ['02','LAB CAMPS','合宿と交流','Camps & connections','研究室ではイベントや夏・冬の合宿を通じた交流も行ってきました．いつもと違う場所で，制作や学びをともにする時間です．','The lab has held events and summer and winter camps: opportunities to create, learn and connect in a different setting.'],
 ['03','IN THE FIELD','地域とともにつくる','Create with communities','九戸城VRやインフラツーリズム．現地を知り，地域の知見を学び，伝わる体験へつなげる活動があります．','Kunohe Castle VR and infrastructure tourism connect field knowledge with experiences that communicate local stories.'],
 ['04','SHARE WITH THE WORLD','論文・国際会議で伝える','Share research internationally','英語論文や国際会議で研究を伝える．どんな問いに，どう取り組んだのかを，図とことばで説明します．','Papers and international conferences are opportunities to explain a research question and approach through figures and words.']
 ].map(([n,k,j,e,d,f])=>`<article><span class="activity-number">${n}</span><p class="eyebrow">${k}</p><h3>${t(j,e)}</h3><p>${t(d,f)}</p></article>`).join('')}</div><p class="caption">${t('これまでの活動の紹介です．開催日・見学のご案内はお問い合わせください．','An introduction to lab activities. Contact us for dates and visit arrangements.')}</p></section>`}
window.primaProgress=window.primaProgress||new Set();
function updatePassport(){const n=window.primaProgress.size;const count=document.querySelector('#quest-count');if(!count)return;count.textContent=n+' / 5';document.querySelector('#quest-meter').value=n;document.querySelectorAll('[data-quest]').forEach(b=>{const done=window.primaProgress.has(PRIMA_PROJECTS[+b.dataset.quest].id);b.classList.toggle('completed',done);b.querySelector('.quest-stamp').textContent=done?'✓ DISCOVERED':'';});}
function mountCommunity(){document.querySelectorAll('[data-quest]').forEach(b=>b.onclick=()=>{window.selectResearch(+b.dataset.quest);document.querySelector('#research').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});updatePassport();}
document.addEventListener('prima-discovery',updatePassport);
