'use strict';
// Public research records and image provenance are documented in SOURCES.md.
let lang='ja',activeTopic=0,paperFilter='all';
const t=(ja,en)=>lang==='ja'?ja:en;
const profile='https://souran.iwate-pu.ac.jp/html/100000143_ja.html';
const topics=[
 {tag:'MEDICAL × 3D',label:['医療と3D','Medical & 3D'],title:['平面の画像から、\n立体の理解へ。','From flat images\nto spatial understanding.'],body:['超音波画像と位置計測を組み合わせ、3次元の構造を捉える。携帯型のフリーハンド3D超音波をテーマに、センシングと画像再構成を探究しています。','Combining ultrasound images with position tracking to reconstruct three-dimensional structure. Our work explores sensing and reconstruction for portable freehand 3D ultrasound.'],note:['2026年 / Sensors 掲載','2026 / Published in Sensors'],url:'https://doi.org/10.3390/s26134080',diagram:'ultrasound',steps:[['2D超音波画像','2D ultrasound'],['位置・角度計測','Position & angle'],['3D再構成','3D reconstruction']]},
 {tag:'VISION × AI',label:['社会で働くAI','AI in practice'],title:['小さな違いを、\n大きな手がかりに。','Small differences.\nMeaningful insights.'],body:['カットリンゴに含まれる微小な欠陥の領域分割や、屋外画像からのPM2.5推定。画像の中にある手がかりを取り出し、食品・環境分野の課題に向き合います。','From segmenting tiny defects in sliced apples to estimating PM2.5 from outdoor images, we explore how visual clues can inform food inspection and environmental monitoring.'],note:['2026年 / ACHI 国際会議で発表','2026 / Presented at ACHI'],url:profile,diagram:'vision',steps:[['画像を取得','Capture'],['特徴を抽出','Extract features'],['検出・推定','Detect & estimate']]},
 {tag:'HUMAN × SENSING',label:['人を理解する','Understanding people'],title:['視線と動きから、\n人を知る。','Understand people\nthrough gaze and motion.'],body:['3D視線計測、姿勢推定、非言語コミュニケーションの分析。人の行動を計測し、人とコンピュータの新しい関わり方を考えます。','3D eye tracking, pose estimation and nonverbal communication analysis. We measure human behavior to explore new ways for people and computers to interact.'],note:['Eye tracking / Pose / Interaction','Eye tracking / Pose / Interaction'],url:'https://www.prima-lab.org/general-5',diagram:'human',steps:[['視線・身体','Gaze & body'],['計測・分析','Measure & analyze'],['インタラクション','Interaction']]},
 {tag:'SPACE × EXPERIENCE',label:['空間と体験','Spaces & experiences'],title:['画面の向こうを、\n体験できる世界に。','Beyond the screen.\nInto the experience.'],body:['球面ディスプレイ「Sphericul」やVRなど、3Dの表現と操作を探究。情報を見るだけでなく、空間の中で関わる体験へと広げます。','Sphericul, our spherical display, and virtual reality explore new ways to present and interact with 3D content—bringing information into shared spatial experiences.'],note:['Sphericul / VR / 3D interaction','Sphericul / VR / 3D interaction'],url:'https://www.prima-lab.org/',image:'assets/sphericul.jpg',alt:['海岸風景を表示する球面ディスプレイSphericul','Sphericul spherical display showing a coastline'],steps:[['3Dコンテンツ','3D content'],['空間へ表示','Spatial display'],['体験・操作','Experience & interact']]}
];
const papers=[
 {year:2026,type:'journal',title:'Portable Freehand 3D Breast Ultrasound Using a Dual-Rotary-Encoder 2DoF Tracking Framework',authors:'S. A. Irfan & O. D. A. Prima',venue:'Sensors · 26(13), 4080',url:'https://doi.org/10.3390/s26134080',desc:['位置・角度の計測と超音波画像をつなぐ3D再構成。','Linking pose tracking and ultrasound images for 3D reconstruction.']},
 {year:2026,type:'journal',title:'ORITRIP: Enhancing Person Re-IDentification with Orientation-Aware Triplet Loss',authors:'T. Q. Nguyen, S. A. Irfan, O. D. A. Prima, T. Pal, N. G. M. Thao & D. T. M. Nguyen',venue:'HUIT Journal of Science · pp. 332–342',url:'https://doi.org/10.62985/j.huit_ojs.vol26.no2E.404',desc:['人物の向きを考慮した再識別の研究。','Person re-identification with orientation-aware learning.']},
 {year:2026,type:'conference',title:'Semantic Segmentation of Extremely Small Defects in Sliced Apples',authors:'Y. Shi & O. D. A. Prima',venue:'ACHI 2026 · pp. 17–22',url:profile,desc:['カットリンゴの微小欠陥を画素単位で捉える。','Pixel-level segmentation of tiny defects in sliced apples.']},
 {year:2026,type:'conference',title:'Vision-Based Estimation of PM2.5 from Surveillance Images',authors:'D. Mitra & O. D. A. Prima',venue:'ACHI 2026 · pp. 35–40',url:profile,desc:['屋外カメラ画像から環境情報を読み解く。','Exploring environmental information in outdoor camera images.']},
 {year:2021,type:'journal',title:'3D Gaze on Stationary and Moving Visual Targets in Mixed Reality Environments',authors:'K. Kato & O. D. A. Prima',venue:'International Journal on Advances in Life Sciences · 13, pp. 104–113',url:'https://www.prima-lab.org/general-5',desc:['複合現実空間における静止・移動対象への視線。','3D gaze toward stationary and moving targets in mixed reality.']},
 {year:2021,type:'journal',title:'Evaluations and Applications of Partial Body Joint Model in 3D Human Pose Estimation from Single Image',authors:'Y. Ono, O. D. A. Prima & K. Hosogoe',venue:'International Journal on Advances in Life Sciences · 13, pp. 114–123',url:'https://www.prima-lab.org/general-5',desc:['単一画像を用いた部分身体モデルの評価と応用。','Evaluating partial-body models for single-image 3D pose estimation.']}
];
function diagram(kind){
 const labels=kind==='ultrasound'?['2D','POSE','3D']:kind==='vision'?['IMAGE','FEATURE','OUTPUT']:['GAZE','MOTION','INSIGHT'];let shape='';
 if(kind==='ultrasound'){for(let i=0;i<7;i++)shape+=`<path d="M${116+i*12} ${75+i*4}l108 34v110l-108-34z" fill="#77c6b4" fill-opacity=".12" stroke="#426f60" stroke-opacity=".5"/>`;shape+='<path d="M102 230l200 60m-30-186l65-28" stroke="#426f60" stroke-dasharray="4 5"/>';}
 else if(kind==='vision'){for(let j=0;j<9;j++)for(let i=0;i<14;i++){const defect=(i-8)**2+(j-4)**2<6;shape+=`<rect x="${75+i*17}" y="${70+j*17}" width="13" height="13" rx="2" fill="${defect?'#365e47':'#8bad8f'}" opacity="${defect?1:.2+((i*3+j*5)%7)/12}"/>`;}shape+='<rect x="183" y="104" width="84" height="84" fill="none" stroke="#304e35" stroke-width="2" stroke-dasharray="6 4"/>';}
 else shape='<path d="M75 170L220 115L330 170M75 170L220 235L330 170M220 115V235" fill="none" stroke="#467664" stroke-width="2"/><circle cx="75" cy="170" r="15" fill="#426f60"/><circle cx="330" cy="170" r="15" fill="#426f60"/><circle cx="220" cy="115" r="11" fill="#769c7e"/><circle cx="220" cy="235" r="11" fill="#769c7e"/><circle cx="210" cy="170" r="45" fill="none" stroke="#426f60" stroke-dasharray="4 5"/>';
 return `<svg viewBox="0 0 410 330" role="img" aria-label="${t('研究の処理の流れを表す概念図。実験データではありません。','Conceptual research workflow, not experimental data.')}"><g>${shape}</g><g font-family="monospace" font-size="12" fill="#34574a"><text x="40" y="32">${labels[0]}</text><text x="173" y="32">${labels[1]}</text><text x="319" y="32">${labels[2]}</text><path d="M102 28h42m102 0h42" stroke="#7a9789"/><text x="35" y="308">CONCEPT / ${kind.toUpperCase()}</text></g></svg>`;
}
function renderTopic(focus=false){
 document.querySelector('#research-tabs').innerHTML=topics.map((p,i)=>`<button role="tab" id="topic-${i}" aria-selected="${i===activeTopic}" aria-controls="research-panel" tabindex="${i===activeTopic?0:-1}" data-topic="${i}"><span>0${i+1} / ${p.tag.split(' × ')[0]}</span>${p.label[lang==='ja'?0:1]}</button>`).join('');
 const p=topics[activeTopic],idx=lang==='ja'?0:1;const panel=document.querySelector('#research-panel');panel.setAttribute('aria-labelledby',`topic-${activeTopic}`);
 panel.innerHTML=`<div class="research-copy"><p class="eyebrow">0${activeTopic+1} / ${p.tag}</p><h3>${p.title[idx].replace('\n','<br>')}</h3><p>${p.body[idx]}</p><div class="topic-meta">${p.note[idx]}</div><a class="text-link" href="${p.url}" target="_blank" rel="noopener">${t('関連する研究・論文を見る ↗','Explore the research ↗')}</a></div><div><div class="research-diagram">${p.image?`<img src="${p.image}" alt="${p.alt[idx]}" width="1920" height="1080" loading="lazy">`:diagram(p.diagram)}</div><div class="process">${p.steps.map((s,i)=>`<span><small>0${i+1}</small>${s[idx]}</span>`).join('')}</div><p class="caption">${p.image?t('研究室の実際の研究画像：Sphericul','Research image from PRIMA LAB: Sphericul'):t('研究の考え方を示す概念図','A conceptual illustration of the research approach')}</p></div>`;
 document.querySelectorAll('[data-topic]').forEach(b=>{b.addEventListener('click',()=>{activeTopic=+b.dataset.topic;renderTopic(true)});b.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();activeTopic=e.key==='Home'?0:e.key==='End'?3:(activeTopic+(e.key==='ArrowRight'?1:3))%4;renderTopic(true)}})});if(focus)document.querySelector(`#topic-${activeTopic}`).focus();
}
function renderPapers(){const visible=papers.filter(p=>paperFilter==='all'||p.type===paperFilter);document.querySelector('#paper-list').innerHTML=visible.map(p=>`<article class="paper"><div class="paper-year">${p.year}<span>${p.type==='journal'?'JOURNAL':'CONFERENCE'}</span></div><div><h3><a href="${p.url}" target="_blank" rel="noopener">${p.title}<span class="paper-arrow" aria-hidden="true">↗</span></a></h3><p class="paper-desc">${p.desc[lang==='ja'?0:1]}</p><p class="authors">${p.authors}</p><p class="venue">${p.venue}</p></div></article>`).join('');document.querySelector('#paper-count').textContent=t(`${visible.length}件の研究成果`,`${visible.length} selected publications`);document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===paperFilter)))}
function renderExtended(){document.querySelector('#extended-content').innerHTML=`
 <section class="feature"><div class="feature-image"><img src="assets/kunohe-castle-vr.jpg" width="750" height="450" alt="${t('九戸城VRで再現された歴史的な景観','Historical landscape reconstructed in Kunohe Castle VR')}" loading="lazy"><span>FIELD NOTES / KUNOHE CASTLE VR</span></div><div class="feature-copy"><p class="eyebrow">LOCAL QUESTIONS. NEW PERSPECTIVES.</p><h2>${t('地域の記憶を、<br>未来の体験へ。','Local heritage.<br>New experiences.')}</h2><p>${t('二戸市との地域共同研究から生まれた九戸城VR。現地調査や史料、専門家の知見をもとに、失われた風景を仮想空間で再構成しました。','Kunohe Castle VR emerged from collaboration with Ninohe City. Field surveys, historical materials and expert knowledge inform a virtual reconstruction of the landscape.')}</p><a class="text-link" href="https://prima-lab-ipu.github.io/kunohe-web/index.html" target="_blank" rel="noopener">${t('九戸城VRプロジェクトへ ↗','Explore Kunohe Castle VR ↗')}</a></div></section>
 <section id="publications" class="section publications"><div class="section-heading"><div><p class="eyebrow">02 / SELECTED PUBLICATIONS</p><h2>${t('問いを、世界へ。','Questions worth sharing.')}</h2></div><a class="text-link" href="${profile}" target="_blank" rel="noopener">${t('大学の研究業績一覧 ↗','Full university research profile ↗')}</a></div><div class="paper-tools"><div class="filters" aria-label="${t('論文の種類','Publication type')}">${[['all','すべて','All'],['journal','学術雑誌','Journal'],['conference','国際会議','Conference']].map(([id,j,e])=>`<button data-filter="${id}" aria-pressed="${paperFilter===id}">${t(j,e)}</button>`).join('')}</div><span id="paper-count" role="status"></span></div><div id="paper-list"></div><p class="publication-note">${t('公開済みの論文から抜粋。書誌情報・掲載区分はリンク先で確認できます。','Selected published works. Follow each link for the bibliographic record and publication details.')}</p></section>
 <section id="people" class="section people"><div class="section-heading"><div><p class="eyebrow">03 / LIFE & PEOPLE</p><h2>${t('好奇心を、研究に変える場所。','A place for curious minds.')}</h2></div><p>${t('一つの専門に、閉じこもらない。<br>つくることから、次の問いが始まる。','Make, investigate, reflect.<br>Find the next question through creation.')}</p></div><div class="people-grid"><article class="pi"><p class="eyebrow">PRINCIPAL INVESTIGATOR</p><h3>Oky Dicky<br>Ardiansyah Prima</h3><p>${t('プリマ オキ ディッキ アルディアンシャー<br>教授 · 博士（工学）','Professor · Ph.D. in Engineering')}</p><p>${t('岩手県立大学 ソフトウェア情報学部','Faculty of Software and Information Science<br>Iwate Prefectural University')}</p><a class="text-link" href="${profile}" target="_blank" rel="noopener">${t('教員プロフィール ↗','Faculty profile ↗')}</a></article><div class="values"><article><span>01</span><div><h3>${t('分野をつなぐ。','Connect disciplines.')}</h3><p>${t('画像処理、AI、センシング、インタラクション。ソフトウェアとものづくりを行き来する研究に出会えます。','Explore image processing, AI, sensing and interaction through both software and physical prototypes.')}</p></div></article><article><span>02</span><div><h3>${t('世界に伝える。','Share with the world.')}</h3><p>${t('英語論文や国際会議での発信も研究の一部。実装したものを評価し、伝わる言葉と図にすることへ。','Research also means evaluating what you build and communicating it through clear figures, papers and international conferences.')}</p></div></article><article><span>03</span><div><h3>${t('研究室の外へ。','Step beyond the lab.')}</h3><p>${t('地域での実践や、研究室のイベント・合宿。人との出会いや現場の体験が、新しい発想につながります。','Community projects, lab events and camps bring people and ideas together beyond the usual research setting.')}</p></div></article></div></div></section>
 <section id="join" class="section join"><div><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>${t('次の「やってみたい」を、<br>ここから。','Bring your curiosity.<br>Build what’s next.')}</h2><p>${t('学生の皆さん、研究者の方、企業・地域の皆さま。<br>気になる研究や、試してみたいアイデアをお聞かせください。','Students, researchers and partners from industry and the community:<br>tell us about your interests and the ideas you want to explore.')}</p><a class="button dark" href="mailto:prima.lab.ipu@gmail.com?subject=${encodeURIComponent(t('PRIMA研究室へのお問い合わせ','Inquiry to PRIMA LAB'))}">${t('見学・研究について相談する　↗','Talk to us about research or a visit　↗')}</a><p class="email">prima.lab.ipu@gmail.com</p></div><div class="contact-details"><p>PRIMA RESEARCH LABORATORY</p><address>${t('岩手県立大学 ソフトウェア情報学部<br>岩手県滝沢市巣子152-52','Faculty of Software and Information Science<br>Iwate Prefectural University<br>152-52 Sugo, Takizawa, Iwate, Japan')}</address><a href="tel:+81196942534">+81 19 694 2534</a><a class="text-link" href="https://www.iwate-pu.ac.jp/" target="_blank" rel="noopener">${t('岩手県立大学 ↗','Iwate Prefectural University ↗')}</a></div></section>`;
 document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{paperFilter=b.dataset.filter;renderPapers()}));renderPapers();
}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-ja]').forEach(e=>e.textContent=e.dataset[lang].replaceAll('\\n','\n'));document.querySelector('#language').innerHTML=lang==='ja'?'EN <span>↗</span>':'JP <span>↗</span>';document.querySelector('#language').setAttribute('aria-label',lang==='ja'?'Switch to English':'日本語に切り替える');document.title=t('PRIMA LAB — 見えない可能性を、かたちに。','PRIMA LAB — See beyond. Create what’s next.');document.querySelector('meta[name="description"]').content=t('岩手県立大学 PRIMA研究室。画像AI、3Dセンシング、視線計測、インタラクションの研究をご紹介します。','PRIMA LAB at Iwate Prefectural University. Explore computer vision, AI, 3D sensing, eye tracking and human-computer interaction.');canvas.setAttribute('aria-label',t('ドラッグや下のスライダーで回転できる3次元点群の概念図','Conceptual 3D point cloud. Drag or use the slider to rotate.'));renderTopic();renderExtended()}
document.querySelector('#language').addEventListener('click',()=>{lang=lang==='ja'?'en':'ja';translate();try{localStorage.setItem('prima-language',lang)}catch{}});try{if(localStorage.getItem('prima-language')==='en')lang='en'}catch{}translate();document.querySelector('#year').textContent=new Date().getFullYear();
document.addEventListener('visibilitychange',()=>{if(document.hidden){spinning=false;document.querySelector('#motion').setAttribute('aria-pressed','false')}});
