'use strict';
function mountPlayground(host,project,language){
 const en=language==='en',idx=en?1:0,T=(a,b)=>en?b:a;
 const captions={ultrasound:['公開超音波画像1枚を仮想位置に並べる操作体験です。実際の連続断面・3D再構成ではありません。画像：Mikael Häggström / CC0。','One public ultrasound image placed at virtual positions. This is not a real slice sequence or 3D reconstruction. Image: Mikael Häggström / CC0.'],wifi:['模擬の信号と骨格による概念体験。実際のWi-Fi計測・DensePose推論ではありません。','Synthetic signals and a skeleton model, not real Wi-Fi measurements or DensePose inference.'],tree:['単純化した枝分かれのモデル。実際の木の成長予測ではありません。','A simplified branching model, not a prediction of real tree growth.'],drawing:['模擬図面を使った処理の概念体験。実際のScanMapのAI処理ではありません。','A synthetic drawing demonstration, not ScanMap AI processing.'],infra:['抽象化した橋と見学ルートの例。実在する施設の再現ではありません。','An abstract bridge and tour route, not a reconstruction of an actual facility.']};
 let value=25,alt=false,yaw=-.45,pitch=.2,drag=null,disposed=false,spinning=true,frameId=0,lastTime=performance.now(),visible=true;
 const slices=new Set(),scan=new Image();if(project.id==='ultrasound'){scan.src='assets/ultrasound-liver.jpg';scan.onload=()=>render();scan.onerror=()=>{host.querySelector('.scan-feedback').textContent=T('画像を読み込めませんでした。再読み込みしてください。','Image unavailable. Please reload.');};}
 host.innerHTML=`<div class="playground"><div class="playground-top"><span>PLAY / ${project.id.toUpperCase()}</span><span>${project.id==='ultrasound'?'IMAGE × VIRTUAL SPACE':T('模擬データ','SYNTHETIC DATA')}</span></div>${project.id==='ultrasound'?`<div class="scan-source"><img src="assets/ultrasound-liver.jpg" width="794" height="585" alt="${T('公開された肝臓の超音波画像','Public ultrasound image of a liver')}"><div><span>01 / SOURCE IMAGE</span><p>${T('この画像を、空間のどこに置く？','Where will you place this image in space?')}</p><small>${T('スライダーで位置を選び、断面を保存。','Choose a position, then save a slice.')}</small></div></div>`:''}<canvas class="demo-canvas" aria-label="${project.label[idx]} ${T('の3D概念モデル。下の操作部で変更できます。','3D concept model. Use the controls below.')}" role="img"></canvas><div class="demo-hint">${T('ドラッグで回転 · 下のボタンでも視点を変更','Drag to rotate · or use the view buttons below')}</div><div class="view-presets" role="group" aria-label="${T('モデルの視点','Model viewpoint')}"><button data-view="front">${T('正面','Front')}</button><button data-view="side">${T('横','Side')}</button><button data-view="under">${T('下から','Below')}</button><button class="demo-motion" aria-pressed="true">${T('回転を停止','Pause rotation')}</button><button data-view="reset">${T('リセット','Reset')}</button></div><div class="demo-controls"><label for="demo-value">${project.control[idx]}<output id="demo-readout" for="demo-value"></output></label><input id="demo-value" type="range" min="0" max="100" value="25">${project.id==='ultrasound'?`<div class="scan-capture"><button class="capture-slice">${T('＋ この位置に断面を保存','+ Save slice here')}</button><span class="scan-feedback" aria-live="polite">0 / 6</span></div><div class="slice-slots" aria-label="${T('保存位置','Saved positions')}">${Array.from({length:6},(_,i)=>`<button data-slot="${i}" aria-pressed="false">${i+1}</button>`).join('')}</div>`:''}<label class="demo-toggle"><input id="demo-toggle" type="checkbox">${project.toggle[idx]}</label></div></div><div class="demo-result" aria-live="polite"><span id="demo-status"></span><p id="demo-insight"></p></div><p class="caption">${captions[project.id][idx]}${project.id==='ultrasound'?' <a class="source-credit" href="https://commons.wikimedia.org/wiki/File:Ultrasonography_of_a_normal_liver.jpg" target="_blank" rel="noopener">Wikimedia Commons ↗</a>':''}</p>`;
 const canvas=host.querySelector('canvas'),slider=host.querySelector('#demo-value'),toggle=host.querySelector('#demo-toggle');

 function updateSlices(){if(project.id!=='ultrasound')return;host.querySelector('.scan-feedback').textContent=slices.size+' / 6';host.querySelectorAll('[data-slot]').forEach(b=>{b.classList.toggle('saved',slices.has(+b.dataset.slot));b.setAttribute('aria-pressed',String(+b.dataset.slot===Math.round(value/20)));});}
 function drawSlices(ctx,project3){const current=Math.round(value/20),planes=[...new Set([...slices,current])].map(i=>({i,z:-.8+i*.32})).sort((a,b)=>project3([0,0,a.z]).z-project3([0,0,b.z]).z);for(const {i,z} of planes){const a=project3([-.85,.65,z]),b=project3([.85,.65,z]),c=project3([-.85,-.65,z]),d=project3([.85,-.65,z]);if(scan.complete&&scan.naturalWidth){ctx.save();ctx.globalAlpha=slices.has(i)?(alt?.35:.8):.2;ctx.transform((b.x-a.x)/scan.width,(b.y-a.y)/scan.width,(c.x-a.x)/scan.height,(c.y-a.y)/scan.height,a.x,a.y);ctx.drawImage(scan,0,0);ctx.restore();}ctx.strokeStyle=i===current?'#d6ff68':'#70d4df';ctx.lineWidth=i===current?2:1;ctx.beginPath();[a,b,d,c].forEach((p,j)=>j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.fillStyle='#d6ff68';ctx.font='11px sans-serif';ctx.fillText(String(i+1),a.x,a.y-7);}}
 if(project.id==='ultrasound'){host.querySelector('.capture-slice').onclick=()=>{if(!scan.naturalWidth)return;slices.add(Math.round(value/20));updateSlices();render();};host.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{value=+b.dataset.slot*20;slider.value=value;updateSlices();render();});slider.addEventListener('input',updateSlices);updateSlices();}
 function render(){if(disposed)return;const {ctx,w,h}=Lab3D.surface(canvas);const project3=Lab3D.projector(w,h,yaw,pitch,Math.min(w/3.8,h/3.15));
 const g=project.id==='ultrasound'?Lab3D.geom():Lab3D.model(project.id,value,alt);if(project.id==='ultrasound'&&alt)g.lines.forEach(l=>{if(l.color===Lab3D.C.blue)l.width=2.5});
 const grid=Lab3D.geom();for(let i=-5;i<=5;i++){Lab3D.line(grid,[-1.25,-1.1,i*.25],[1.25,-1.1,i*.25],'#243c4c',.6);Lab3D.line(grid,[i*.25,-1.1,-1.25],[i*.25,-1.1,1.25],'#243c4c',.6)}Lab3D.paint(ctx,grid,project3);Lab3D.paint(ctx,g,project3);if(project.id==='ultrasound')drawSlices(ctx,project3);
 let label,done;
 if(project.id==='ultrasound'){label=T(`位置 ${Math.round(value/20)+1} / 6`,`Position ${Math.round(value/20)+1} / 6`);done=slices.size===6&&Math.abs(Math.sin(yaw))>.8;}
 if(project.id==='wifi'){label=`${value}%`;done=value>=50&&alt;}
 if(project.id==='tree'){label=T(`段階 ${(1+value/25).toFixed(1)}`,`Stage ${(1+value/25).toFixed(1)}`);done=value>=65&&alt;}
 if(project.id==='drawing'){const kept=Array.from({length:100},(_,i)=>(i*37%101)/100).filter(x=>x>=value/100*.92).length;label=T(`背景点 ${kept} / 100`,`Background ${kept} / 100`);done=value>=70&&alt;}
 if(project.id==='infra'){label=[T('入口','Entrance'),T('構造を観察','Inspect structure'),T('地域を眺める','Look at the landscape')][Math.min(2,Math.floor(value/34))];done=value>=90&&pitch<-.25;}
 host.querySelector('#demo-readout').textContent=label;
 if(done&&!window.primaProgress.has(project.id)){window.primaProgress.add(project.id);document.dispatchEvent(new Event('prima-discovery'));}
 const status=done?T('発見！次は条件を変えてみよう。','Discovery! Now try different conditions.'):T('小さな実験を、ここから。','Start a small experiment.');if(host.querySelector('#demo-status').textContent!==status)host.querySelector('#demo-status').textContent=status;
 host.querySelector('.demo-result').classList.toggle('achieved',done);if(host.querySelector('#demo-insight').textContent!==project.insight[idx])host.querySelector('#demo-insight').textContent=project.insight[idx];
 }
 slider.addEventListener('input',()=>{value=+slider.value;render()});toggle.addEventListener('change',()=>{alt=toggle.checked;render()});
 host.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{pause();switch(b.dataset.view){case'front':yaw=0;pitch=0;break;case'side':yaw=1.3;pitch=.1;break;case'under':yaw=.55;pitch=-.5;break;default:yaw=-.45;pitch=.2;value=25;alt=false;slider.value=25;toggle.checked=false;slices.clear();updateSlices();}render()});
 canvas.addEventListener('pointerdown',e=>{pause();drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.008;pitch=Math.max(-1,Math.min(1,pitch+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];render()});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>canvas.addEventListener(ev,()=>drag=null));
 const motion=host.querySelector('.demo-motion');
 function syncMotion(){motion.textContent=spinning?T('回転を停止','Pause rotation'):T('自動回転','Auto rotate');motion.setAttribute('aria-pressed',String(spinning));}
 function pause(){spinning=false;cancelAnimationFrame(frameId);syncMotion();}
 function frame(time){if(disposed||!spinning||document.hidden||!visible)return;yaw+=(Math.min(40,time-lastTime))*.00022;lastTime=time;render();frameId=requestAnimationFrame(frame);}
 function resume(){cancelAnimationFrame(frameId);if(spinning&&!document.hidden&&visible){lastTime=performance.now();frameId=requestAnimationFrame(frame);}}
 motion.onclick=()=>{spinning=!spinning;syncMotion();resume();};
 document.addEventListener('visibilitychange',resume);
 const viewport=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;resume();});viewport.observe(canvas);
 const observer=new ResizeObserver(render);observer.observe(canvas);render();resume();return()=>{disposed=true;cancelAnimationFrame(frameId);scan.onload=null;scan.onerror=null;observer.disconnect();viewport.disconnect();document.removeEventListener('visibilitychange',resume)};
}
